In [5]:
import numpy as np

In [6]:
# 1. Create a 3x3 array that contains a diagonal of nines.
frist = np.full((3,3),9)

In [7]:
print (frist)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [8]:
# 2. Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive) and use boolean indexing to pick out the values that are within 1/2 standard deviations of the mean.
second = np.arange(2, 33, 2).reshape(4, 4)
mean = np.mean(second)
std_dev = np.std(second)

In [9]:
half_std_dev = second[(second > mean - 0.5 * std_dev) & (second < mean + 0.5 * std_dev)]

In [10]:
print(half_std_dev)

[14 16 18 20]


In [11]:
# 3. Create a 9x9 array that contains only zeros of type int.
third = np.zeros((9, 9), dtype=int)
print(third)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [12]:
# 4. Ask the user for a number n. Then, use broadcasting to create a n x n ndarray that has its first column full of ones, its second column full of twos, its third column full of threes, etc…
n = int(input("Enter a number n:"))
fourth = np.tile(np.arange(1, n + 1), (n, 1))

Enter a number n: 5


In [13]:
print (fourth)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


## A . Sereja and Dima

In [14]:
# https://codeforces.com/contest/381/problem/A
n = int(input())
cards = np.array(list(map(int, input().split())))

sereja_points = 0
dima_points = 0
left = 0
right = n - 1

while left <= right:
    if cards[left] > cards[right]:
        sereja_points += cards[left]
        left += 1
    else:
        sereja_points += cards[right]
        right -= 1

    if left <= right:
        if cards[left] > cards[right]:
            dima_points += cards[left]
            left += 1
        else:
            dima_points += cards[right]
            right -= 1
            
print(sereja_points, dima_points)

  4
   4 1 2 10


12 5


## A. Brain's Photos

In [3]:
# https://codeforces.com/contest/707/problem/A
n, m = map(int, input().split())
photo_matrix = [input().split() for _ in range(n)]

photo_array = np.array(photo_matrix)

colors = set(np.unique(photo_array))
color_set = {'C', 'M', 'Y'}
if colors.intersection(color_set):
    print("#Color")
else:
    print("#Black&White")

 2 2 
 C M
  Y Y


#Color


In [4]:
n, m = map(int, input().split())
photo_matrix = [input().split() for _ in range(n)]

photo_array = np.array(photo_matrix)

colors = set(np.unique(photo_array))
color_set = {'C', 'M', 'Y'}
if colors.intersection(color_set):
    print("#Color")
else:
    print("#Black&White")

 3 2
  W W 
 W W
  B B


#Black&White
